---
title: "Others"
---


## Resources 

* [R, Rstudio による統計解析 __PDF__](RAnalysis.pdf)  : 学部生用にツールとしての使い方を簡潔にまとめたものです。
* [Inquisit uninstall page (Japanese)](https://sites.google.com/view/inquisit-player-uninstall/%e3%83%9b%e3%83%bc%e3%83%a0?subjectid=1  )：
InquistのWeb実験で使う __Inquisit 5 Player__ のアンインストール方法を書いたサイトです。内容ご確認の上，ご自由にリンクしてください。


* [個人的なQ & A __PDF__](QA_20200609.pdf) (new.gif):
私は学んだ翌日にはほぼ忘れる人間なので，2019年からメモをまとめ始めました。特によく使う事項や，解決策を見つけるのに苦労した内容を載せています。お役に立つ情報があれば幸いです。

* [オンライン実験備忘録 __PDF__](オンライン実験備忘録.pdf)  (new.gif):

こちらの備忘録は，**Qualtrics**で質問紙調査，**Inquisit**で行動課題，**クラウドワークス社**のシステムを利用してWEB実験を行う際の情報を載せています。それぞれの基本的な使い方については省略し，これらをWEB実験で組み合わせる際の方法に焦点を当てています。名古屋大学の片平先生の研究室での研究方法をまとめまたものになります。常にこうしたものはバージョンが更新されていくものですので，最新の情報に注意してご参考になさってください。


    
**内容に誤りを見つけられた方は，遠山(asako.toyama[at]gmail.com)までご連絡頂けますと幸いです。



    
  

## Link
#### Nagoya University 

* [School of Informatics, Graduate School of Informatics](https://www.i.nagoya-u.ac.jp/en/)
* [Computational Behavioral Science Laboratory](https://sites.google.com/site/nagoyacbslab/home)
* [Natuki Saito (psychologist of empathy)](https://n-saito.amebaownd.com/)  

#### Useful sites
* [日本心理学会第83回大会 チュートリアル・ワークショップ004 機械学習と心理学の接点の補足資料(片平先生)](https://kkatahira.github.io/personality/index.html)
    
  