---
title: "Profile"
output:
  html_document:
    toc_float: false
---

> 学位

* 2019年5月(令和元)　博士（心理学）名古屋大学
* 2013年3月(平成25)　修士（心理学）名古屋大学
* 2008年3月(平成20)　学士（ 文学 ）京都大学


> 学歴

* 2013(平成25)年4月ー2016(平成29)年3月　名古屋大学大学院　環境学研究科　博士後期課程　（単位取得満期退学）
* 2011(平成23)年4月ー2013(平成26)年3月　名古屋大学大学院　環境学研究科　博士前期課程
* 2004(平成16)年4月ー2008(平成20)年3月　京都大学文学部　人文学科　
* 2003(平成16)年3月　福岡県立修猷館高等学校　卒業

> 職歴

* 2024(令和 6)年4月ー　一橋大学　社会科学高等研究院 講師
* 2023(令和 5)年8月ー　一橋大学　ソーシャル・データサイエンス研究科　特任助教
* 2020(令和 2)年4月ー2023(令和5)年7月　日本学術振興会　特別研究員（PD）受入研究機関：専修大学　文学研究科　国里研究室
* 2017(平成29)年4月ー2020(平成30)年3月　名古屋大学 情報学研究科　研究員（大平研究室） 
* 2015(平成27)年4月ー2017(平成30)年3月　日本学術振興会　特別研究員（DC2）名古屋大学　大平研究室
* 2013(平成25)年4月ー2016(平成29)年3月　名古屋大学大学院 ティーチングアシスタント
* 2012(平成24)年4月ー2015(平成28)年3月　名古屋大学 環境医学研究所附属近未来環境シミュレーションセンター 技術職員
* 2008(平成20)年4月ー2011(平成23)年3月　理化学研究所 事務職員      

> 教育歴

- 継続中
  - なし

- 以前
  - 2021（令和3）年4月1日ー2023(令和5)年8月　 専修大学　非常勤講師　[心理学基礎実験]
  - 2020（令和2）年9月21日ー2023(令和5)年8月　専修大学　非常勤講師　[心理学英文購読] 
  - 2021（令和3）年4月1日ー2023(令和5)年3月　専修大学　非常勤講師　[基礎心理学特殊講義：感情・動機づけ・情動]
  - 2016（平成28）年4月ー2020(令和 2)年3月　名古屋大学 文学部 非常勤講師 [基礎心理学演習]

> 学会ならびに社会における活動

- 2012年4月23日～現在　　日本心理学会　会員 
- 2012年2月 1日～現在　　日本生理心理学会　会員
- 2021年～現在  CPSYMAP（：計算論的精神医学の論文データベース）エディター，ならびにCPSY TOKYOのチュータ


> 外部資金

- 日本学術振興会　特別研究員奨励費 　研究代表
  -  PD (20J01464)「忘却過程を考慮した強化学習モデルによる計算論的精神医学研究」（研究代表者）2020年度-2022年度（中断期間を含み2023年度7月末まで）
  -  DC (15J10796)「報酬の相対的価値とそれを補正する心理神経メカニズム」（研究代表者）2015年度-2016年度


- その他　研究代表
  - 平成 30 年度科学研究費補助金（若手研究 18K13366）「意思決定における価値計算過程と選択過程を分離して評価する計算論的アプローチ」（研究代表者）, 2018年度–2021年度
        	  
- その他　分担	
  
  - CREST [マルチセンシング] 2021年度採択課題，研究領域：「生体マルチセンシングシステムの究明と活用技術の創出」，研究総括：入來 篤史，研究課題名：「多様な迷走神経情報から創発する内受容感覚の脳統合」研究代表者：佐々木 拓哉，2021年度-2026年度
  
  - 基盤研究(A) 21H04420「内受容感覚の予測的処理を基盤とした感情と意思決定の創発メカニズムの探求」研究代表者：大平英樹，2021年度–2024年度.
  
  - 国際共同研究加速基金(国際共同研究強化(B))「予測的符号化に基づく計算論的心身医学ー過敏性腸症候群を対象とした基礎的検討ー」代表者：大平英樹，2019年度–2023年度

-------------------------

> Current affiliation (2023.8~)
* Graduate School of Social Data Science, Hitotsubashi University, 2-1 Naka, Kunitachi, Tokyo 186-8601, Japan

> Previous affiliation (~2023.7)
* Japan Society for the Promotion of Science, Tokyo, Japan
* Graduate School of the Humanities, Senshu University, kawasaki, Japan




